name: App CI
on:
  push:
    paths: ['Hoxtup-app/**']
  pull_request:
    paths: ['Hoxtup-app/**']

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Hoxtup-app
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: Hoxtup-app/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm generate:api
      - run: pnpm test
